version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Amazon Linux uses yum instead of apt-get
      - yum update -y
      - yum install -y zip unzip
      
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Compressing files for deployment..."
      # Create zip without including the buildspec.yml and other CI/CD files
      - zip -r webapp.zip * -x "buildspec.yml" -x "*.git*"
      
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Artifact: webapp.zip created successfully"

artifacts:
  files:
    - 'webapp.zip'
  discard-paths: yes
  